name: Build and Deploy

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Gitea Container Registry
        run: >-
          echo "${{ secrets.REGISTRY_TOKEN }}"
          | docker login 10.77.0.20 -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t 10.77.0.20/greenland/yomiage:latest \
            -t 10.77.0.20/greenland/yomiage:${{ github.sha }} \
            .

      - name: Push Docker image
        run: |
          docker push 10.77.0.20/greenland/yomiage:latest
          docker push 10.77.0.20/greenland/yomiage:${{ github.sha }}

      - name: Deploy to YUNAGI
        uses: appleboy/ssh-action@v1
        with:
          host: 10.77.0.17
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          envs: REGISTRY_TOKEN
          script: |
            IMAGE="10.77.0.20/greenland/yomiage:latest"

            # Giteaレジストリ認証
            echo "$REGISTRY_TOKEN" | sudo podman login --tls-verify=false 10.77.0.20 -u ${{ github.actor }} --password-stdin

            # 旧コンテナ停止・削除（初回デプロイ時は存在しないのでエラー無視）
            sudo podman stop greenland-yomiage 2>/dev/null || true
            sudo podman rm greenland-yomiage 2>/dev/null || true

            # 最新イメージ取得
            sudo podman pull --tls-verify=false $IMAGE

            # コンテナ起動
            sudo podman run -d \
              --name greenland-yomiage \
              --restart always \
              --env-file /opt/greenland-yomiage/.env \
              -v /opt/greenland-yomiage/data:/app/data:Z \
              $IMAGE

            # ヘルスチェック（10秒後にコンテナが生存しているか）
            sleep 10
            if sudo podman ps --filter name=greenland-yomiage --format '{{.Status}}' | grep -q 'Up'; then
              echo "Deploy successful: container is running"
            else
              echo "Deploy FAILED: container is not running"
              sudo podman logs greenland-yomiage
              exit 1
            fi
        env:
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

      - name: Cleanup old registry versions (keep latest 20)
        if: always()
        run: |
          API="http://10.77.0.20/api/v1/packages/greenland/container/yomiage"
          TOKEN="${{ secrets.REGISTRY_TOKEN }}"

          # SHA タグのバージョンを作成日降順で取得し、20件より古いものを削除
          curl -s -H "Authorization: token $TOKEN" \
            "http://10.77.0.20/api/v1/packages/greenland?type=container&limit=50&sort=created_desc" \
          | python3 -c "
          import json, sys, urllib.request

          data = json.load(sys.stdin)
          # latest と sha256: を除いたコミットSHAタグのみ抽出
          sha_versions = [p for p in data if p['name'] == 'yomiage'
                          and not p['version'].startswith('sha256:')
                          and p['version'] != 'latest']
          # 新しい順にソート
          sha_versions.sort(key=lambda x: x['created_at'], reverse=True)

          # 20件より古いものを削除
          to_delete = sha_versions[20:]
          for v in to_delete:
              ver = v['version']
              url = f'$API/{ver}'
              req = urllib.request.Request(url, method='DELETE')
              req.add_header('Authorization', 'token $TOKEN')
              try:
                  urllib.request.urlopen(req)
                  print(f'Deleted: {ver}')
              except Exception as e:
                  print(f'Failed to delete {ver}: {e}')

          if not to_delete:
              print('No old versions to delete')
          "

      - name: Cleanup CI host
        if: always()
        run: |
          docker rmi 10.77.0.20/greenland/yomiage:latest 2>/dev/null || true
          docker rmi 10.77.0.20/greenland/yomiage:${{ github.sha }} 2>/dev/null || true
          docker builder prune -f 2>/dev/null || true
